// Bilibili Subtitle Extractor
// Uses Bilibili's public API to fetch subtitles
// No content script needed - runs in extension context with host_permissions

const BilibiliExtractor = {
  name: 'Bilibili',

  canHandle(url) {
    return /^https?:\/\/(www|m)\.bilibili\.com\/video\//.test(url)
      || /^https?:\/\/b23\.tv\/BV[a-zA-Z0-9]+/.test(url);
  },

  getBvid(url) {
    const match = url.match(/(?:\/video\/|b23\.tv\/)(BV[a-zA-Z0-9]+)/);
    return match ? match[1] : null;
  },

  getPage(url) {
    try {
      const u = new URL(url);
      return parseInt(u.searchParams.get('p') || '1', 10);
    } catch {
      return 1;
    }
  },

  async _getVideoInfo(bvid) {
    const response = await fetch(
      `https://api.bilibili.com/x/web-interface/view?bvid=${bvid}`
    );
    const data = await response.json();
    if (data.code !== 0) return null;
    return data.data;
  },

  async _getCid(bvid, page) {
    const info = await this._getVideoInfo(bvid);
    if (!info) return null;

    const pages = info.pages || [];
    if (page > 1 && pages.length >= page) {
      return { cid: pages[page - 1].cid, aid: info.aid, title: info.title };
    }
    return { cid: info.cid, aid: info.aid, title: info.title };
  },

  async getAvailableLanguages(url) {
    try {
      const bvid = this.getBvid(url);
      if (!bvid) return [];

      const page = this.getPage(url);
      const cidInfo = await this._getCid(bvid, page);
      if (!cidInfo) return [];

      const response = await fetch(
        `https://api.bilibili.com/x/player/v2?bvid=${bvid}&cid=${cidInfo.cid}`
      );
      const data = await response.json();
      if (data.code !== 0) return [];

      const subtitles = data.data?.subtitle?.subtitles;
      if (!subtitles || subtitles.length === 0) return [];

      return subtitles.map(sub => ({
        code: sub.lan,
        name: sub.lan_doc,
        url: sub.subtitle_url.startsWith('//') ? 'https:' + sub.subtitle_url : sub.subtitle_url,
        isAutoGenerated: sub.type === 1
      }));
    } catch (e) {
      console.error('[BilibiliExtractor] getAvailableLanguages error:', e);
      return [];
    }
  },

  async getTranscript(subtitleUrl) {
    if (!subtitleUrl) return null;

    try {
      const response = await fetch(subtitleUrl);
      const data = await response.json();

      if (!data.body || data.body.length === 0) return null;

      return data.body.map(item => ({
        start: item.from,
        duration: item.to - item.from,
        text: item.content.trim()
      }));
    } catch (e) {
      console.error('[BilibiliExtractor] getTranscript error:', e);
      return null;
    }
  }
};
